version: '3.8'
services:
  user-db:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  contest-db:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    environment:
      POSTGRES_DB: contest
      POSTGRES_USER: contest
      POSTGRES_PASSWORD: contest
    ports:
      - "5434:5432"
    volumes:
      - pgdata_contest:/var/lib/postgresql/data
    restart: always
  vote-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always
  kafka-broker:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    restart: always
volumes:
  pgdata: {}
  pgdata_contest: {}
  mongodb-data: {}
  pgdata_vote: {}